#!/bin/sh

files=`git diff --cached --name-status --diff-filter=ACMR -- '***.py' | awk '/^[ACMR]/ {print $2}'`
echo "$files" | xargs isort --check-only && \
echo "$files" | xargs black --check --diff && \
echo "$files" | xargs flake8
