# Generated by Django 4.0.5 on 2022-06-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0003_sesso_statodonatore_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donatore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_tessera", models.CharField(max_length=255)),
                ("cognome", models.CharField(max_length=255)),
                ("nome", models.CharField(max_length=255)),
                (
                    "num_tessera_cartacea",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "data_rilascio_tessera",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "codice_fiscale",
                    models.CharField(blank=True, max_length=255),
                ),
                ("data_nascita", models.DateField(blank=True, null=True)),
                ("data_iscrizione", models.DateField(blank=True, null=True)),
                (
                    "gruppo_sanguigno",
                    models.CharField(blank=True, max_length=10),
                ),
                ("rh", models.CharField(blank=True, max_length=10)),
                ("fenotipo", models.CharField(blank=True, max_length=10)),
                ("kell", models.CharField(blank=True, max_length=10)),
                ("indirizzo", models.CharField(blank=True, max_length=255)),
                ("frazione", models.CharField(blank=True, max_length=255)),
                ("cap", models.CharField(blank=True, max_length=10)),
                ("comune", models.CharField(blank=True, max_length=255)),
                ("provincia", models.CharField(blank=True, max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=255)),
                (
                    "telefono_lavoro",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cellulare", models.CharField(blank=True, max_length=255)),
                ("fax", models.CharField(blank=True, max_length=255)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("fermo_per_malattia", models.BooleanField(default=False)),
                ("donazioni_pregresse", models.IntegerField(default=0)),
                ("num_benemerenze", models.IntegerField(default=0)),
                (
                    "sesso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="avis.sesso",
                    ),
                ),
                (
                    "sezione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="donatori",
                        to="avis.sezione",
                    ),
                ),
                (
                    "stato_donatore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="avis.statodonatore",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Donatori",
                "unique_together": {("sezione", "num_tessera")},
            },
        ),
    ]
