# Generated by Django 4.0.5 on 2022-06-12 16:12

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0004_donatore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donazione',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'tipo_donazione',
                    models.IntegerField(
                        choices=[
                            (None, 'Non specificato'),
                            (1, 'Sangue intero'),
                            (2, 'Plasma'),
                            (3, 'Piastrine'),
                        ],
                        default='Non specificato',
                        null=True,
                    ),
                ),
                (
                    'data_donazione',
                    models.DateField(default=datetime.date.today),
                ),
                (
                    'donatore',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='donazioni',
                        to='avis.donatore',
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Donazioni',
                'unique_together': {('donatore', 'data_donazione')},
            },
        ),
    ]
