# Generated by Django 4.2.dev20220708064602 on 2022-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0006_alter_donazione_tipo_donazione"),
    ]

    operations = [
        migrations.AddField(
            model_name="sezione",
            name="data_stampa_benemerenze",
            field=models.DateField(
                blank=True,
                help_text="Data da usare per la stampa delle benemerenze,"
                " se non specificata, verrà usata la data corrente.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sezione",
            name="luogo_stampa_benemerenze",
            field=models.CharField(
                blank=True,
                help_text="Luogo da usare per la stampa delle benemerenze,"
                " se non specificato, verrà usato il comune della sezione.",
                max_length=100,
            ),
        ),
    ]
