# Generated by Django 4.1 on 2022-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0012_alter_donazione_tipo_donazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatore',
            name='scheda_anamnestica',
            field=models.TextField(blank=True),
        ),
    ]
