# Generated by Django 4.1 on 2022-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0014_donatore_motivo_inattivita'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatore',
            name='stampa_donatore',
            field=models.BooleanField(default=False),
        ),
    ]
