# Generated by Django 4.2.1 on 2023-05-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0015_donatore_stampa_donatore"),
    ]

    operations = [
        migrations.AddField(
            model_name="statodonatore",
            name="can_export_elenco_soci_xls",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Include i donatori in questo stato nell'export dell'elenco soci"
                ),
                verbose_name="Includi in Elenco Soci Excel",
            ),
        ),
    ]
