# Generated by Django 4.2.1 on 2023-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0016_statodonatore_can_export_elenco_soci_xls"),
    ]

    operations = [
        migrations.AddField(
            model_name="donatore",
            name="causa_cessata_iscrizione",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="donatore",
            name="data_cessata_iscrizione",
            field=models.DateField(blank=True, null=True),
        ),
    ]
