# Generated by Django 4.2.1 on 2023-06-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0017_donatore_data_cessata_iscrizione"),
    ]

    operations = [
        migrations.AddField(
            model_name="donatore",
            name="check_privacy",
            field=models.BooleanField(
                default=False, verbose_name="Modulo privacy compilato e consegnato"
            ),
        ),
        migrations.AddField(
            model_name="donatore",
            name="check_privacy_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data compilazione e consegna modulo privacy",
            ),
        ),
    ]
