# Generated by Django 4.2.5 on 2023-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0018_donatore_check_privacy_donatore_check_privacy_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donazione",
            name="tipo_donazione",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Non specificato"),
                    (1, "Sangue intero"),
                    (2, "Plasma"),
                    (4, "Eritro-Plasmaferesi"),
                    (5, "Eritrociti"),
                ],
                default="Non specificato",
                null=True,
            ),
        ),
    ]
