# Generated by Django 5.2.3 on 2025-06-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("avis", "0019_alter_donazione_tipo_donazione"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donatore",
            old_name="num_benemerenze",
            new_name="num_benemerenze_consegnate",
        ),
    ]
