# Generated by Django 5.2.3 on 2025-06-23 18:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avis", "0020_rename_num_benemerenze_donatore_num_benemerenze_consegnate"),
    ]

    operations = [
        migrations.AddField(
            model_name="sezione",
            name="configurazione_benemerenze",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(),
                blank=True,
                default=list,
                help_text=(
                    "Configurazione delle benemerenze conseguite "
                    "(valori numerici interi, separati da virgola)."
                ),
                size=None,
            ),
        ),
    ]
