# Generated by Django 5.2.17 on 2026-09-16 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avis", "0021_sezione_configurazione_benemerenze"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("chiamato", "Chiamato"),
                            ("non_risponde", "Non risponde"),
                            ("richiamare", "Richiamare"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="nota"),
                ),
                (
                    "focus_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (None, "Non specificato"),
                            (1, "Sangue intero"),
                            (2, "Plasma"),
                            (4, "Eritro-Plasmaferesi"),
                            (5, "Eritrociti"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donatore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="avis.donatore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Esito chiamata",
                "verbose_name_plural": "Esiti chiamate",
                "ordering": ("-created_at",),
            },
        ),
    ]
