name: Django CI

env:
  PYTHON_VERSION: '3.9'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pipenv'
    - name: Downloading 3rd party libs
      run: make get-static-libs
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        make requirements
    - name: Run Tests
      run: |
        pipenv run make style-check
        pipenv run make tests
