name: Django CI

env:
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'poetry'
    - name: Downloading 3rd party libs
      run: make get-static-libs
    - name: Install Dependencies
      run: |
        make requirements
    - name: Run Tests
      run: |
        make style-check
        make tests
