name: Django CI

env:
  DB_NAME: test_db
  DB_USER: test_user
  DB_PASSWORD: test_password

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v5
    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install
    - name: Downloading 3rd party libs
      run: make get-static-libs
    - name: Install Dependencies
      run: |
        make requirements
    - name: Run Tests
      run: |
        make style-check
        make tests
      env:
        SECRET_KEY: '12345678901234567890123456789012345678901234567890'
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_NAME: ${{ env.DB_NAME }}
        DB_USER: ${{ env.DB_USER }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
